scheduler:
  ip: "10.131.40.45"
  commands: 
    - "date"
    - |-
      /home/etdev/Report_Script/sxm_profile_w_encryption_v1_4.py
      {{if .ScheduleTime}}--schedule-time={{.ScheduleTime}}{{end}} 
      {{if .Source}}--source={{.Source}}{{end}} 
      {{if gt (len .Destinations) 0}}--destinations {{range .Destinations}}{{.}} {{end}}{{end}}

sdvn:
  ip: "10.131.40.20"
  background: > 
      tail -n 0 -f /var/log/magrtrsrv.log > sxm_router.txt & 
      tail -n 0 -f /var/log/magclientsrv.log > sxm_client.txt
  commands: 
    - "python3 route_speed_from_logs.py -syslog=10.131.40.31 sxm_router.txt 0 --check-magclient-requests sxm_client.txt"

slab:
  commands: 
    - "sleep 180"
    - |-
      python3 slab_logs_script.py 
      --analytics-ip=127.0.0.1 
      --json-output 
      {{if .Multicast}}--ip-mcast-source={{.Multicast}}{{end}} 
      {{if .Source}}--broadview-source={{.Source}}{{end}} 
      {{if .RouteMapData}}--router-data {{.RouteMapData}}{{else}}--router-map=routermap.json{{end}} 