scheduler:
  ip: "10.9.0.69"
  commands: 
    - "date"
    - "python3 scheduler_script.py"
    - "echo Done with scheduler"

sdvn:
  ip: "10.9.0.69"
  background: > 
      tail -n 0 -f /var/log/magrtrsrv.log > sxm_router.txt & 
      tail -n 0 -f /var/log/magclientsrv.log > sxm_client.txt
  commands: 
    - "python3 sdvn_script.py"
    - "echo Done with sdvn"

slab:
  commands: 
    - "python3 slab_logs_script.py -map routermap.json -mcast 239.131.1.161 -insite 10.9.0.69"
    - "echo Done with slab"