scheduler:
  ip: "10.9.1.69"
  commands: 
    - "python3 scheduler_script.py"
    - "echo Done with scheduler"

sdvn:
  ip: "10.9.0.69"
  commands: 
    - "python3 sdvn_script.py"
    - "echo Done with sdvn"